# Netlify configuration for Vite + React SPA
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback so client-side routing works on refresh and deep links
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: local dev via `netlify dev` (will proxy to Vite)
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "vite"

# Security headers (CSP) for production on Netlify
# Remarque: adaptez les sources si vous supprimez les CDN
[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://cdn.jsdelivr.net https://aistudiocdn.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
